
set -g @minimal_theme_bg_color        "#fff8f6"
set -g @minimal_theme_active_color    "#99461d"
set -g @minimal_theme_inactive_color  "#d8c2ba"
set -g @minimal_theme_text_color      "#201a18"
set -g @minimal_theme_accent_color    "#77574a"
set -g @minimal_theme_border_color    "#f2e5e1"

