source-file ~/.config/tmux/generated.conf

run-shell ~/.config/tmux/plugins/tmux-minimal-theme/minimal.tmux
run-shell ~/.config/tmux/plugins/tmux-which-key/which-key.tmux

set -g default-shell /usr/bin/fish

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'


# set -g @which-key-config '~/.config/tmux-which-key/config.json'
set -g @plugin 'Nucc/tmux-which-key'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
