source-file ~/.config/tmux/generated.conf
source-file ~/.config/tmux/keybinds.conf

run-shell ~/.config/tmux/plugins/tmux-minimal-theme/minimal.tmux
# run-shell ~/.config/tmux/plugins/tmux-which-key/which-key.tmux

set -g default-shell /usr/bin/fish

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:Tc"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'


# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

setw -g mode-keys vi
set -g status-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel 'pbcopy'
